apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: qg-flask
  name: qg-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qg-flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qg-flask
    spec:
      containers:
      - image: mj0098/qg-bart:1.2
        name: qg-bart
        ports:
        - containerPort: 4000
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: qg-flask
  name: qg-flask
spec:
  loadBalancerIP: 192.168.1.12
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: qg-flask
  type: LoadBalancer
status:
  loadBalancer: {}

